openapi: 3.0.0
info:
  title: My Echo API
  version: 1.0.0
paths:
  /api/v1/hello:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: A greeting to the caller
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
